### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by pkelleratwork** [CircleCI-Public/config-preview-sdk#124]
trying to move to version 2.1 - getting this error and documentation is not helping. these work with version 2.0. am i seriously expected to rewrite yamls to bump a minor release?

```

Config Processing Error00:00
Exit code: 1
#!/bin/sh -eo pipefail
# There is an error in the config file
# jobs: 10 schema violations found
#   jobs: Deploy Staging: string [Deploy Staging] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Push Release: string [Push Release] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Deploy QA: string [Deploy QA] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Deploy Dev: string [Deploy Dev] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Deploy Demo: string [Deploy Demo] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Build: string [Build] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Unit Tests: string [Unit Tests] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Push Latest: string [Push Latest] does not match pattern ^[a-z][a-z\\d_-]*$
#   jobs: Deploy PROD: string [Deploy PROD] does not match pattern ^[a-z][a-z\\d_-]*$
false
```

**Comment by pkelleratwork** [comment]
nevermind - figured out CCI is no longer supporting jobs with caps or spaces. - was that a missed flag or is it really dropped support?

**Comment by ndintenfass** [comment]
This was actually an inadvertent change, and we'll be fixing it very soon. In the mean time you can work around it by using lower case names, but we will be shipping a change to allow all job names from 2.0 to work. (FYI, internal CircleCI folks: this is the ticket: CIRCLE-14408)

**Comment by ndintenfass** [comment]
I'm going to reopen this, so we can track it for others.

**Comment by ndintenfass** [comment]
This should now be fixed. Please let us know if you experience problems.
