### ISSUE TITLE
unable to publish orb by other organization users

### ISSUE THREAD

**Issue by piotr-s-brainhub** [CircleCI-Public/config-preview-sdk#126]
circleci version: 0.1.3723+1dca9bc
OS: Mac OS X 10.12.6

one of my organization users is able to publish orb but another not

```
⟩ circleci setup
✔ A CircleCI token is already set. Do you want to change it: y
✔ CircleCI API Token: ****************************************
API token has been set.
✔ CircleCI Host: https://circleci.com
CircleCI host has been set.
Setup complete. Your configuration has been saved.

⟩ circleci orb publish base.orb.yml my-org/base@1.1.3
Error: User does not have access to publish SemVer orbs in this namespace.
```

Settings allow other users to publish a new orb
![download](https://user-images.githubusercontent.com/20856232/47939548-09068000-dee8-11e8-858a-c83ab0fd6ea3.png)

**Comment by yundt** [comment]
Hello, @piotr-s-brainhub. It appears our wording under "Allow Uncertified Orbs" opt-in is confusing - one [needs to be an organization administrator](https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/orbs-authoring.md#dev-and-production-orbs-have-different-security-profiles) to publish production (SemVer) orbs.

Could you please check whether the user in question is this organization's administrator?

**Comment by piotr-s-brainhub** [comment]
@yundt 

the user which cannot publish is not an administrator

**Comment by yundt** [comment]
@piotr-s-brainhub thank you for checking that! I'm closing the issue, as this is the expected behavior. We'll reconsider wording of the "Allow Uncertified Orbs" switch, though - thank you for letting us know about this!
