### ISSUE TITLE
Are there effects of having "version: 2.1" and "workflow.version: 2" in the same `.circleci/config.yml`?

### ISSUE THREAD

**Issue by augustohp** [CircleCI-Public/config-preview-sdk#129]
I am new to CircleCI and I haven't found much referece towards `workflow.version: 2` other than its presence on all examples in the documenation.

Should I change `workflow.version: 2` to `workflow.version: 2.1` when using `version: 2.1` or can I leave it?

**Comment by eric-hu** [comment]
Hi Augusto, you can leave `workflow.version: 2` as-is or delete that line with `version: 2.1`. If deleted, the config processing will fill it back in before running your build.

**Comment by marcomorain** [comment]
Yeah - for full context, the `version: 2` key that is allowed in 2.1 under workflows is vestigial, and will be removed at some point in the future. For now we allow to allow for backwards compatibility with 2.0 config.
