### ISSUE TITLE
Setting and accessing job names

### ISSUE THREAD

**Issue by devurandom** [CircleCI-Public/config-preview-sdk#130]
1. How do I set the job name from within a job?
  - My job names can be constructed from the job's parameters: https://github.com/lualdap/lualdap/blob/ea225de021c96173434ac819133ad77a04699e68/.circleci/config.yml#L57-L58
2. How do I access the job name from within a job?
  - I would like to pass on the job name to another service via a command: https://github.com/lualdap/lualdap/blob/ea225de021c96173434ac819133ad77a04699e68/.circleci/config.yml#L40

**Comment by ndintenfass** [comment]
The short answer is you can’t. In this case, the name you provide in the workflow would be used only in the workflow for making coordinating dependent jobs (that is, so you could reference the job name in a `requires` stanza to have jobs follow execution of other jobs.)
