### ISSUE TITLE
2.1 with the API? Trigger jobs?

### ISSUE THREAD

**Issue by bendavies** [CircleCI-Public/config-preview-sdk#132]
Hey there,

I'm using the new parametrized jobs in 2.1 to great effect. However, the circle ci API doesn't seem to like the 2.1 grammar.

For jobs that are fine through the web interface, triggering via the API with something like:
```
curl -u ${CIRCLE_API_USER_TOKEN}: \
     -d build_parameters[CIRCLE_JOB]=deploy \
     -d build_parameters[foo]=bar \
     https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>
```
will return an error from the API:
```
Your config file has errors and may not run correctly:<br/><pre>21 schema violations found<br/>  jobs: deploy: extraneous key [parameters] is not permitted<br/> etc...
```

Is this a current limitation or am i missing something?

thanks.

**Comment by ndintenfass** [comment]
Yes, it's a limitation of that API endpoint. We have a new endpoint for triggering a build that will work with the 2.1 features, but it doesn't (yet) allow build parameters. See: https://circleci.com/docs/api/v1-reference/#new-project-build

**Comment by bendavies** [comment]
that's a shame. i'll revert to 2.0 for now then

**Comment by bendavies** [comment]
hey @ndintenfass was the above implemented? I can't work it out from the docs. Thanks!

**Comment by rob4629** [comment]
Hey @ndintenfass... since build parameters aren't currently supported for 2.1, does that mean we can only trigger `build` jobs via the API??

**Comment by sridhar-vadlamani-ck** [comment]
2.1 doesn't work with the API, last I knew. And circleCI's v2.0 api has been "coming soon" for about an year and a half now. They really dropped the ball on this.

**Comment by rob4629** [comment]
Yeah, finally came across this thread:
https://ideas.circleci.com/ideas/CCI-I-690

**Comment by kirillgroshkov** [comment]
Yes, will need to revert to 2.0 probably. Shame.
