### ISSUE TITLE
update docs for creating and publishing orbs

### ISSUE THREAD

**Issue by ksteiny** [CircleCI-Public/config-preview-sdk#32]
I have been going through these docs all morning. LOVE the orb feature. But I can't figure out how to actually create and publish an orb. Tried walking through https://github.com/CircleCI-Public/circleci-orbs. The cli is different so there is no build/register cmds.

should i be able to create and publish custom orbs now or is that feature just not ready yet?

**Comment by ndintenfass** [comment]
Sorry for the confusion. We planned to have full orb publishing ready, but it will be a few days. In the mean time check out inline orbs, which lets you author them in your config.yml, and later you’ll be able to swap it out.

**Comment by ksteiny** [comment]
np! thanks for the clarification. ill go down that path for now.
