### ISSUE TITLE
Unclear "Getting Started" Section in Readme

### ISSUE THREAD

**Issue by Bloodyaugust** [CircleCI-Public/config-preview-sdk#40]
It took me a while to figure out that the "Getting Started" sections in the docs and Readme were different: that the Readme docs were incomplete. Specifically, to figure out that in addition to enabling processing in the "Advanced" config in the web UI, I needed to update the `version` property as well (and there was no error reporting in my failed workflows that indicated this was the issue).

Perhaps a link in the Readme to the doc version with an aside about "more details" or something would be helpful, or just reproducing the doc version in the Readme.

**Comment by ndintenfass** [comment]
#53 addresses this.
