### ISSUE TITLE
Executing shell commands directly in "steps"

### ISSUE THREAD

**Issue by ylemkimon** [CircleCI-Public/config-preview-sdk#51]
There are several examples which execute shell commands directly in the `steps`:

https://github.com/CircleCI-Public/config-preview-sdk/blob/41a9d5b64619419baf76b09f662d502757de61b5/docs/jobs.md#L29-L30

https://github.com/CircleCI-Public/config-preview-sdk/blob/41a9d5b64619419baf76b09f662d502757de61b5/docs/jobs.md#L63-L64

https://github.com/CircleCI-Public/config-preview-sdk/blob/41a9d5b64619419baf76b09f662d502757de61b5/docs/jobs.md#L107-L108

https://github.com/CircleCI-Public/config-preview-sdk/blob/41a9d5b64619419baf76b09f662d502757de61b5/docs/parameters.md#L17-L18

Is this a feature not implemented yet or a typo (missing `run:`)?

**Comment by ndintenfass** [comment]
Thank you for pointing these out @ylemkimon - you are correct that these are bugs in the samples. We'll get that fixed soon.

**Comment by ndintenfass** [comment]
Fixed by https://github.com/CircleCI-Public/config-preview-sdk/pull/55
