### ISSUE TITLE
Conditional Build Steps at Runtime

### ISSUE THREAD

**Issue by lswith** [CircleCI-Public/config-preview-sdk#69]
I read the documentation outlined here and I'm excited for the features as this is going to solve a lot of headache for us atm!

The only thing left that I really feel is a must have feature besides allow more reusability of configuration, is the ability to dynamically declare the workflow based on a previous workflow.

Let's say I have Project A, Project B and Project C in a repository with 1 shared CircleCI configuration.

I would want there to be a workflow that determines if Project A, Project B and Project C require a build. Once this workflow runs, it would then kick off any futher workflows for Project A, Project B or Project C.

**Comment by ndintenfass** [comment]
Agreed that this would be very valuable. I'm closing this here because it's not the best place for us to track the feature, but you should vote on this "Idea": https://circleci.com/ideas/?idea=CCI-I-273 (or create another if I'm wrong that it captures your request)
