### ISSUE TITLE
ror: key not valid?

### ISSUE THREAD

**Issue by drazisil** [CircleCI-Public/config-preview-sdk#71]
In https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/inline-orbs.md

The sample fails with `Error: Cannot find circleci/rails@volatile in the orb registry. Check that the namespace, orb name and version are correct.` when using version `0.1.2231+249a3d6` of the CLI.

Further, I can find no other references of `ror` in this repo. Is this outdated syntax? Could it have some more detailed docs if still valid?

**Comment by eric-hu** [comment]
I'm not seeing a mention of a `ror` or `rails` orb on that page. Is that the correct link? We did write some early docs with this, so we should clean this up if it's on another page.

As for a rails orb, we don't have one yet. I did some early prototyping before we built out orb syntax, and @bradylill currently has the Rails orb cards active on the Orbs JIRA board. I'm not sure what the current state of that is, though--Brady?

**Comment by drazisil** [comment]
@eric-hu Sorry, URL corrected.

**Comment by eric-hu** [comment]
Thanks @drazisil , I've added PR #72 to refer to an existing orb.

**Comment by eric-hu** [comment]
Just merged #72 , closing this. Lmk if there's anything not addressed in this issue @drazisil
