### ISSUE TITLE
config 2.1 migration issues

### ISSUE THREAD

**Issue by rshriram** [CircleCI-Public/config-preview-sdk#77]
Hi, here is our config (https://github.com/istio/istio/blob/master/.circleci/config.yml)
I tried changing the version from 2 to 2.1
As you can see, our config has a lot of here doc commands for commonly used YAML snippets..
Per the caveats section, I changed these heredoc `<<` to use `\<<` - but `circleci config validate` spews out a lot of errors like
```
 jobs: e2e: -dashboard-mcponly 0 subschema matches out of 2
    jobs: e2e: -dashboard-mcpextraneous key [\<<] is not permitted
    jobs: e2e: -dashboard-mcpno subschema matched out of the total 2 subschemas
      jobs: e2e: -dashboard-mcprequired key [executor] not found
      jobs: e2e: -dashboard-mcp0 subschemas matched instead of one
        jobs: e2e: -dashboard-mcprequired key [machine] not found
        jobs: e2e: -dashboard-mcprequired key [docker] not found
        jobs: e2e: -dashboard-mcprequired key [macos] not found
```

If I don't replace the `<<` with `\<<`, I get a different validation error from the CLI (when I change the version to 2.1)
```Error: Cannot find a definition for a command named command```

**Comment by rshriram** [comment]
Update: I converted all the heredoc yaml stuff to commands. The `circleci config validate` says the configuration is valid (see config https://github.com/istio/istio/blob/circleci_21/.circleci/config.yml ).. 
But it fails when running in circleci
https://circleci.com/gh/istio/istio/195314#tests/containers/0
```
Build-agent version 0.1.709-11d8fb06 (2018-09-07T17:05:01+0000)
Configuration errors: 1 error occurred:

* In step 2 definition: step type "mark_job_starts_on_gcs" is not a valid type
```

**Comment by ndintenfass** [comment]
We recently made a number of changes that might fix this. Can you please try again, and let us know if you continue to have this problem?

**Comment by ndintenfass** [comment]
@rshriram I'm going to close this soon as we get ready to move the docs. I am hoping your problem was fixed a few weeks back, but if you see this and can confirm or deny that would be helpful.

**Comment by rshriram** [comment]
Hi sorry for the late response. We can't move to 2.1 yet. So, will close the issue for now.
