### ISSUE TITLE
Confusing orbs-cd docs

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/config-preview-sdk#90]
The following sentences are confusing. What kind of validate command is to be used when and why?

`Note that, because the compiled code is run through CircleCI's workflow conductor, orb-tools/publish-dev-orb requires validate-orb, instead of orb-tools/validate-orb.`

`orb-tools/validate uses the CLI to validate a given orb yml. Example usage.` -> pointing to an example with `orb-tools/validate-orb`

**Comment by matfax** [comment]
It also appears that `orb-tools/publish-dev-orb` and `orb-tools/publish-release-orb` are switched.

**Comment by bradylill** [comment]
#96
