### ISSUE TITLE
Dev version does not accept camelCase names

### ISSUE THREAD

**Issue by nmiyake** [CircleCI-Public/config-preview-sdk#97]
Based on the documentation and messages, I would expect any content to be valid after `dev:` in a version. However, it appears that `camelCase` names are rejected:

```
➜ circleci orb publish ./src/go/orb.yml palantir/go@dev:masterBranch --token <token>
Error: Invalid version specified for publishing: dev:masterBranch (expected either a semver-style version string in x.y.z format, or a development-style version string in dev:* format.)
```

Performing the same operation with the same name in all lowercase works:

```
➜ circleci orb publish ./src/go/orb.yml palantir/go@dev:masterbranch --token <token>
Orb `palantir/go@dev:masterbranch` was published.
```

This appears to be an error on the server-side -- I added some debugging code to the CLI and the error is returned after submitting the GraphQL request (https://github.com/CircleCI-Public/circleci-cli/blob/master/api/api.go#L538).

**Comment by ndintenfass** [comment]
This should be fixed now. Please let us know if you still have issues.
